---
- hosts: tag_solution_webserver_magchr
  become: yes
  vars:
    websiteheader: "Ansible Playbook"
    websiteauthor: "Magnus R. Christoffersen"
  tasks:
    - name: Install Apache
      dnf:
        name: httpd
        state: latest
    
    - name: Enabled Apache
      systemd:
        name: httpd
        enabled: yes
        state: started
    
    - name: Allow http in firewall
      firewalld:
        zone: public
        service: http
        permanent: yes
        state: enabled
        immediate: yes
      notify:
        - reload firewall
    
    - name: add index.htl
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
    
  handlers:
    - name: reload firewall
      service:
        name: firewalld
        state: reloaded